[module]
  [[module.exports]]
    path = "layouts"
  [[module.exports]]
    path = "assets"
  [[module.exports]]
    path = "i18n"
  [[module.exports]]
    path = "archetypes"
  [[module.exports]]
    path = "data/themes"   # bare paletter, ikke person-CV
